### ISSUE TITLE
The About page

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/running-stories#11]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | About Running Stories |
| User Story | The about page |

## Description
As a website visitor, I want to understand the purpose of the running stories website so that I can engage with the content effectively.

## Acceptance Criteria
1. The “About” page prominently displays a brief overview of the website’s purpose.
2. The content is written in plain language, avoiding technical jargon.
3. The “About” page provides a link or button to explore more running stories.
4. The page layout is visually appealing and easy to read.

## Tasks
- [x] Create an about template, model, page etc.
- [x] Write a compelling and concise description of the website’s purpose.
- [x] Design the layout for the “About” page.
- [ ] Create a link/button to navigate to the main running stories section.
- [x] Write tests for About page
