### ISSUE TITLE
Handle drafts

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/running-stories#13]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | Story Creation |
| User Story | Handle drafts |

## Description
As a user, I want to be able to save my stories as drafts so that I can work on them later.

## Acceptance Criteria
1. Users should be able to save their stories as drafts.
2. When editing a story, users should have the option to publish it.
3. The system should provide a way to view all published stories.
4. There should be a way to identify stories that are still in draft mode.

## Tasks
- [x] Display published stories on the appropriate pages.
- [x] Create views and forms to handle story creation, editing, and publishing.
- [x] Write tests for About page
