### ISSUE TITLE
Create a Running Story

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/running-stories#2]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | Story Creation |
| User Story | Create a Running Story |

## Description
As a registered user, I want to create a running story to share my experiences.

## Acceptance Criteria
1. Given that I am logged in, when I navigate to the “Share Story” page, then I should see a form to input my story details (title, content).
2. Given that I have filled in the story details, when I submit the form, then my story should be saved and visible to other users.

## Tasks
- [x] Create the “Share story” page 
- [x] Create form for story details (title, content etc.).
- [x] Implement the backend logic to save new stories.
- [x] Ensure that only logged-in users can access this feature.
- [x] Ensure navigation menu navigates to Share your story page
- [x] Style "Share story page"
- [x] Write tests for story creation.
