### ISSUE TITLE
View Running Stories

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/running-stories#3]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | Story Viewing |
| User Story | View Running Stories |

## Description
As a user, I want to view running stories posted by others so that I can get inspired of other runners.

## Acceptance Criteria
1. Given that I am on the homepage, then I should see a list of running stories with titles and brief summaries.
2. Given that I click on a story, then I should be taken to the full story page.

## Tasks
- [x] Create a page that displays a full Running story
- [x] Design the full story page to show the complete content.
- [x] Implement pagination if there are many stories.
- [x] Implement ordering, latest first
- [x] Write tests for story listing and viewing.
