### ISSUE TITLE
Visitor View Running Stories

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/running-stories#9]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | Story Viewing |
| User Story | Visitor View Running Stories |

## Description
As a visitor, I want to be able to read running stories so that I can be inspired by others’ experiences.

## Acceptance Criteria
1. When I visit the website, I should see a list of running stories.
2. I should be able to click on a story to read its full content.

## Tasks
- [x] Create a view to display a list of running stories.
- [x] Implement a detail view to show an individual story.
- [x] Design the detail view
- [x] Write tests for editing and deleting stories.
